# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '07_14_kuwahatasachio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 07_14_kuwahatasachio
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'SDWebImage/WebP'
  pod 'FirebaseDatabase'
  pod 'FBSDKLoginKit'
  pod 'SVProgressHUD'

end
